// TWITTER
// const { ApifyClient } = require("apify-client");

// const client = new ApifyClient({
// 	token: "apify_api_2CgreGr9xT0ERXqIQIjrIAx0pc2ixj44FJzb",
// });

// // Prepare Actor input
// const input = {
// 	// searchTerms: ["apify"],
// 	// searchMode: "live",
// 	maxTweets: 15,
// 	maxRequestRetries: 6,
// 	addUserInfo: false,
// 	scrapeTweetReplies: false,
// 	handle: ["@levelsio"],
// 	sinceDate: "2024-04-20",
// 	untilDate: "2024-04-22",
// 	// urls: ["https://twitter.com/search?q=gpt&src=typed_query&f=live"],
// };

// (async () => {
// 	// Run the Actor and wait for it to finish
// 	const run = await client.actor("heLL6fUofdPgRXZie").call(input);

// 	// Fetch and print Actor results from the run's dataset (if any)
// 	console.log("Results from dataset");
// 	const { items } = await client.dataset(run.defaultDatasetId).listItems();
// 	items.forEach((item) => {
// 		console.dir(item);
// 		// retweeted_status_result contains object if it's a retweet
// 	});
// })();

// LINKEDIN
import { ApifyClient } from "apify-client";

// Initialize the ApifyClient with API token
const client = new ApifyClient({
	token: "apify_api_2CgreGr9xT0ERXqIQIjrIAx0pc2ixj44FJzb",
});

// Prepare Actor input
const input = {
	cookie: [
		{
			domain: ".linkedin.com",
			expirationDate: 1716256533,
			hostOnly: false,
			httpOnly: false,
			name: "aam_uuid",
			path: "/",
			sameSite: "unspecified",
			secure: false,
			session: false,
			storeId: "0",
			value: "40574630718997981413908815648748072647",
			id: 1,
		},
		{
			domain: ".linkedin.com",
			expirationDate: 1729216533,
			hostOnly: false,
			httpOnly: false,
			name: "AMCV_14215E3D5995C57C0A495C55%40AdobeOrg",
			path: "/",
			sameSite: "unspecified",
			secure: false,
			session: false,
			storeId: "0",
			value: "-637568504%7CMCIDTS%7C19835%7CMCMID%7C40713047356562948383959165603590118668%7CMCAAMLH-1714269333%7C6%7CMCAAMB-1714269333%7CRKhpRz8krg2tLO6pguXWp5olkAcUniQYPHaMWWgdJ3xzPWQmdj0y%7CMCOPTOUT-1713671733s%7CNONE%7CvVersion%7C5.1.1",
			id: 2,
		},
		{
			domain: ".linkedin.com",
			hostOnly: false,
			httpOnly: false,
			name: "AMCVS_14215E3D5995C57C0A495C55%40AdobeOrg",
			path: "/",
			sameSite: "unspecified",
			secure: false,
			session: true,
			storeId: "0",
			value: "1",
			id: 3,
		},
		{
			domain: ".linkedin.com",
			expirationDate: 1716244299.798534,
			hostOnly: false,
			httpOnly: false,
			name: "AnalyticsSyncHistory",
			path: "/",
			sameSite: "no_restriction",
			secure: true,
			session: false,
			storeId: "0",
			value: "AQIngeKrp2_zNwAAAY79ovhi5Nlf8-yCLEFqPjOWfekGHZJ6SeO3dvWMmX4xpG3_c2m8cbYtp7YA7oc_jse--w",
			id: 4,
		},
		{
			domain: ".linkedin.com",
			hostOnly: false,
			httpOnly: false,
			name: "at_check",
			path: "/",
			sameSite: "no_restriction",
			secure: true,
			session: true,
			storeId: "0",
			value: "true",
			id: 5,
		},
		{
			domain: ".linkedin.com",
			expirationDate: 1745225619.241056,
			hostOnly: false,
			httpOnly: false,
			name: "bcookie",
			path: "/",
			sameSite: "no_restriction",
			secure: true,
			session: false,
			storeId: "0",
			value: '"v=2&95c84f15-c6e2-48ed-8c27-46e31eed7caf"',
			id: 6,
		},
		{
			domain: ".linkedin.com",
			expirationDate: 1741307902.327334,
			hostOnly: false,
			httpOnly: true,
			name: "dfpfpt",
			path: "/",
			sameSite: "lax",
			secure: true,
			session: false,
			storeId: "0",
			value: "7f9f8dca8bf74246a26282b13c127130",
			id: 7,
		},
		{
			domain: ".linkedin.com",
			hostOnly: false,
			httpOnly: true,
			name: "fptctx2",
			path: "/",
			sameSite: "lax",
			secure: true,
			session: true,
			storeId: "0",
			value: "taBcrIH61PuCVH7eNCyH0B9zcK90d%252bIeoo1r5v7Zc25thWWUU9gUOCoWJXOnXKND7qGkLD7G4LR73FTN7b9e8Y0vUEVaw3gNjs0WarPdDqwBzHOBzqcxUq%252btJrhg9GeVDRZFmQGGD9EPBFzqmCI6sCt36puy4Diq7breVd%252ftM3Kn%252bOItZQM69xiKtju5fB67S8RLDYps4LkCK0FOpn0O5Ou2Pw4KRx0NYgeN60EMZLWERNrF7pJIl61AxaHbWuPi4r5Y%252f1iRQZd7v3O29YHt18HP1Pt83AFjbbPPJf%252bHktWPAjoeMDDjJ6ekwrj%252fEfWa34AsQrh6K2s9cMZUk4Y%252bx%252bGC6hRCOaTZZmD%252fRoAX8is%253d",
			id: 8,
		},
		{
			domain: ".linkedin.com",
			expirationDate: 1729217503,
			hostOnly: false,
			httpOnly: false,
			name: "gpv_pn",
			path: "/",
			sameSite: "unspecified",
			secure: false,
			session: false,
			storeId: "0",
			value: "www.linkedin.com%2Flegal%2Fl%2Fmarketing-api-terms",
			id: 9,
		},
		{
			domain: ".linkedin.com",
			hostOnly: false,
			httpOnly: false,
			name: "lang",
			path: "/",
			sameSite: "no_restriction",
			secure: true,
			session: true,
			storeId: "0",
			value: "v=2&lang=en-us",
			id: 10,
		},
		{
			domain: ".linkedin.com",
			expirationDate: 1725323875.001472,
			hostOnly: false,
			httpOnly: false,
			name: "li_gc",
			path: "/",
			sameSite: "no_restriction",
			secure: true,
			session: false,
			storeId: "0",
			value: "MTswOzE3MDk3NzE4NzQ7MjswMjEjBfVaQBh4h+BkSd9QiZhC/Ueonc3hjWzyWsKSa6EibQ==",
			id: 11,
		},
		{
			domain: ".linkedin.com",
			expirationDate: 1729241812.959272,
			hostOnly: false,
			httpOnly: false,
			name: "li_mc",
			path: "/",
			sameSite: "no_restriction",
			secure: true,
			session: false,
			storeId: "0",
			value: "MTsyMTsxNzEzNjg5ODEyOzI7MDIxJWA8k5A1Ivt193R8o7RWCi/fOdue1j+YQfbGZ3GeH+c=",
			id: 12,
		},
		{
			domain: ".linkedin.com",
			expirationDate: 1721465618.240909,
			hostOnly: false,
			httpOnly: false,
			name: "li_sugr",
			path: "/",
			sameSite: "no_restriction",
			secure: true,
			session: false,
			storeId: "0",
			value: "9d8c41b3-3f96-4d3b-9bad-d5bfd1309936",
			id: 13,
		},
		{
			domain: ".linkedin.com",
			expirationDate: 1721465613.463924,
			hostOnly: false,
			httpOnly: false,
			name: "liap",
			path: "/",
			sameSite: "no_restriction",
			secure: true,
			session: false,
			storeId: "0",
			value: "true",
			id: 14,
		},
		{
			domain: ".linkedin.com",
			expirationDate: 1713693499.630464,
			hostOnly: false,
			httpOnly: false,
			name: "lidc",
			path: "/",
			sameSite: "no_restriction",
			secure: true,
			session: false,
			storeId: "0",
			value: '"b=VB63:s=V:r=V:a=V:p=V:g=6097:u=997:x=1:i=1713689618:t=1713693498:v=2:sig=AQHP6BHEYPw6mkoWxnSf9q2Qz1otIQ2n"',
			id: 15,
		},
		{
			domain: ".linkedin.com",
			expirationDate: 1716244299.963911,
			hostOnly: false,
			httpOnly: false,
			name: "lms_ads",
			path: "/",
			sameSite: "no_restriction",
			secure: true,
			session: false,
			storeId: "0",
			value: "AQF5jGvn1gGdYwAAAY79ovkIegrpGQHSQYNvlZtwzPjPlTZQrYZm6KTLts1-00JB29Xb4MESTKI3ENZlyC8heJPvH44bozRi",
			id: 16,
		},
		{
			domain: ".linkedin.com",
			expirationDate: 1716244299.964048,
			hostOnly: false,
			httpOnly: false,
			name: "lms_analytics",
			path: "/",
			sameSite: "no_restriction",
			secure: true,
			session: false,
			storeId: "0",
			value: "AQF5jGvn1gGdYwAAAY79ovkIegrpGQHSQYNvlZtwzPjPlTZQrYZm6KTLts1-00JB29Xb4MESTKI3ENZlyC8heJPvH44bozRi",
			id: 17,
		},
		{
			domain: ".linkedin.com",
			expirationDate: 1729210949,
			hostOnly: false,
			httpOnly: false,
			name: "mbox",
			path: "/",
			sameSite: "no_restriction",
			secure: true,
			session: false,
			storeId: "0",
			value: "PC#12e1065748224c1484cc74e499a266d7.37_0#1729210949|session#d7e0175398c14985876f348c528a3af0#1713660809",
			id: 18,
		},
		{
			domain: ".linkedin.com",
			hostOnly: false,
			httpOnly: false,
			name: "s_cc",
			path: "/",
			sameSite: "unspecified",
			secure: false,
			session: true,
			storeId: "0",
			value: "true",
			id: 19,
		},
		{
			domain: ".linkedin.com",
			expirationDate: 1729217503,
			hostOnly: false,
			httpOnly: false,
			name: "s_fid",
			path: "/",
			sameSite: "unspecified",
			secure: false,
			session: false,
			storeId: "0",
			value: "74280F73C4F966FE-318EEF07F0456794",
			id: 20,
		},
		{
			domain: ".linkedin.com",
			expirationDate: 1729217492,
			hostOnly: false,
			httpOnly: false,
			name: "s_ips",
			path: "/",
			sameSite: "unspecified",
			secure: false,
			session: false,
			storeId: "0",
			value: "1321",
			id: 21,
		},
		{
			domain: ".linkedin.com",
			hostOnly: false,
			httpOnly: false,
			name: "s_plt",
			path: "/",
			sameSite: "unspecified",
			secure: false,
			session: true,
			storeId: "0",
			value: "1.32",
			id: 22,
		},
		{
			domain: ".linkedin.com",
			hostOnly: false,
			httpOnly: false,
			name: "s_pltp",
			path: "/",
			sameSite: "unspecified",
			secure: false,
			session: true,
			storeId: "0",
			value: "www.linkedin.com%2Flegal%2Fl%2Fmarketing-api-terms",
			id: 23,
		},
		{
			domain: ".linkedin.com",
			hostOnly: false,
			httpOnly: false,
			name: "s_ppv",
			path: "/",
			sameSite: "unspecified",
			secure: false,
			session: true,
			storeId: "0",
			value: "www.linkedin.com%2Flegal%2Fl%2Fmarketing-api-terms%2C46%2C8%2C7148%2C6%2C15",
			id: 24,
		},
		{
			domain: ".linkedin.com",
			hostOnly: false,
			httpOnly: false,
			name: "s_sq",
			path: "/",
			sameSite: "unspecified",
			secure: false,
			session: true,
			storeId: "0",
			value: "%5B%5BB%5D%5D",
			id: 25,
		},
		{
			domain: ".linkedin.com",
			expirationDate: 1729218142,
			hostOnly: false,
			httpOnly: false,
			name: "s_tp",
			path: "/",
			sameSite: "unspecified",
			secure: false,
			session: false,
			storeId: "0",
			value: "15651",
			id: 26,
		},
		{
			domain: ".linkedin.com",
			expirationDate: 1729217503,
			hostOnly: false,
			httpOnly: false,
			name: "s_tslv",
			path: "/",
			sameSite: "unspecified",
			secure: false,
			session: false,
			storeId: "0",
			value: "1713665503700",
			id: 27,
		},
		{
			domain: ".linkedin.com",
			hostOnly: false,
			httpOnly: false,
			name: "sdsc",
			path: "/",
			sameSite: "no_restriction",
			secure: true,
			session: true,
			storeId: "0",
			value: "22%3A1%2C1713272607573%7ECONN%2C0qSMyU%2BtjHBVUgZuZan7HY1Hhv2I%3D",
			id: 28,
		},
		{
			domain: ".linkedin.com",
			hostOnly: false,
			httpOnly: false,
			name: "SID",
			path: "/",
			sameSite: "unspecified",
			secure: false,
			session: true,
			storeId: "0",
			value: "1aec17e1-dca8-4f30-8839-7e4055c0f68d",
			id: 29,
		},
		{
			domain: ".linkedin.com",
			expirationDate: 1716281618,
			hostOnly: false,
			httpOnly: false,
			name: "UserMatchHistory",
			path: "/",
			sameSite: "no_restriction",
			secure: true,
			session: false,
			storeId: "0",
			value: "AQKvFoYxG1paDwAAAY7_3GGEbwe5adjVylVe2oBp6nWyelgs2rrDokKpaKghdl8eDeh9F391JGVZmIf3fQtxT2WcLHxP7gfQW236XB0R4c5h8k6QAsvl4H3xo8LVEdknwqRWguyuerLPGSlJjcFqTNnHeY7RuWf3gG_DobsW67YJgPCK6gBjteSQ2r_okszCTyye_vXzfuyGjrVhYxQR_4ilrI_tDNA7XUHRp_xUqIGhlQcDvMUr02oMrjr9Fo8ZnVR8K_R7mOyrolRBpylLEaPVOONQtZ0_kdOd",
			id: 30,
		},
		{
			domain: ".linkedin.com",
			expirationDate: 1745111769.337555,
			hostOnly: false,
			httpOnly: false,
			name: "VID",
			path: "/",
			sameSite: "unspecified",
			secure: false,
			session: false,
			storeId: "0",
			value: "V_2024_04_20_01_1115",
			id: 31,
		},
		{
			domain: ".linkedin.com",
			expirationDate: 1748224517.094941,
			hostOnly: false,
			httpOnly: false,
			name: "visit",
			path: "/",
			sameSite: "no_restriction",
			secure: true,
			session: false,
			storeId: "0",
			value: "v=1&M",
			id: 32,
		},
		{
			domain: ".www.linkedin.com",
			expirationDate: 1745225614.464289,
			hostOnly: false,
			httpOnly: true,
			name: "bscookie",
			path: "/",
			sameSite: "no_restriction",
			secure: true,
			session: false,
			storeId: "0",
			value: '"v=1&20240307003754406263b2-04e7-4c36-8276-1a0779bcfbd9AQH082XpShuJxiyPQArsWdGHIgL3UBSk"',
			id: 33,
		},
		{
			domain: ".www.linkedin.com",
			expirationDate: 1721465613.464128,
			hostOnly: false,
			httpOnly: false,
			name: "JSESSIONID",
			path: "/",
			sameSite: "no_restriction",
			secure: true,
			session: false,
			storeId: "0",
			value: '"ajax:8511133956387182057"',
			id: 34,
		},
		{
			domain: ".www.linkedin.com",
			expirationDate: 1745225613.464015,
			hostOnly: false,
			httpOnly: true,
			name: "li_at",
			path: "/",
			sameSite: "no_restriction",
			secure: true,
			session: false,
			storeId: "0",
			value: "AQEDARqhUKsCP2zNAAABjv_cVEAAAAGPI-jYQE0AGIqU8OxkSTIsEd40lhnobtUC44Plr98neiAQ0dH_iPYu7XBT-g4FfHq2fwEZHxwCAEdsHmxay-mwL9V2O0s8GfsKCGmmqhMSV-nL4guMG_e8z3uZ",
			id: 35,
		},
		{
			domain: ".www.linkedin.com",
			expirationDate: 1745225613.463708,
			hostOnly: false,
			httpOnly: true,
			name: "li_rm",
			path: "/",
			sameSite: "no_restriction",
			secure: true,
			session: false,
			storeId: "0",
			value: "AQGng9tsWgQJBgAAAY7-XWJir872z9SFSsSaWFmL8t2ljchufeRfIGAoaP3-OazvWxRMzj3B_d_AWz6n0locihmS-PsO-Epe3MmklXhFm_7G4MtLqhjQZ9vX",
			id: 36,
		},
		{
			domain: ".www.linkedin.com",
			expirationDate: 1729241615,
			hostOnly: false,
			httpOnly: false,
			name: "li_theme",
			path: "/",
			sameSite: "unspecified",
			secure: true,
			session: false,
			storeId: "0",
			value: "light",
			id: 37,
		},
		{
			domain: ".www.linkedin.com",
			expirationDate: 1729241615,
			hostOnly: false,
			httpOnly: false,
			name: "li_theme_set",
			path: "/",
			sameSite: "unspecified",
			secure: true,
			session: false,
			storeId: "0",
			value: "app",
			id: 38,
		},
		{
			domain: ".www.linkedin.com",
			expirationDate: 1714899215,
			hostOnly: false,
			httpOnly: false,
			name: "timezone",
			path: "/",
			sameSite: "unspecified",
			secure: true,
			session: false,
			storeId: "0",
			value: "Europe/Berlin",
			id: 39,
		},
		{
			domain: "www.linkedin.com",
			expirationDate: 1729241612,
			hostOnly: true,
			httpOnly: false,
			name: "g_state",
			path: "/",
			sameSite: "unspecified",
			secure: false,
			session: false,
			storeId: "0",
			value: '{"i_l":0}',
			id: 40,
		},
		{
			domain: "www.linkedin.com",
			expirationDate: 1745201468,
			hostOnly: true,
			httpOnly: false,
			name: "li_alerts",
			path: "/",
			sameSite: "no_restriction",
			secure: true,
			session: false,
			storeId: "0",
			value: "e30=",
			id: 41,
		},
		{
			domain: "www.linkedin.com",
			hostOnly: true,
			httpOnly: false,
			name: "PLAY_LANG",
			path: "/",
			sameSite: "unspecified",
			secure: false,
			session: true,
			storeId: "0",
			value: "en",
			id: 42,
		},
		{
			domain: "www.linkedin.com",
			hostOnly: true,
			httpOnly: true,
			name: "PLAY_SESSION",
			path: "/",
			sameSite: "lax",
			secure: true,
			session: true,
			storeId: "0",
			value: "eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7InNlc3Npb25faWQiOiI3Nzc5MzhiNy0zZWNlLTQxMDQtODAzNi1lNDkxNDNiYjQzNTh8MTcxMzY2NzE5OSIsImFsbG93bGlzdCI6Int9IiwicmVjZW50bHktc2VhcmNoZWQiOiIiLCJyZWZlcnJhbC11cmwiOiJodHRwczovL3d3dy5saW5rZWRpbi5jb20vaGVscC9saW5rZWRpbi9hbnN3ZXIvYTUyNjA0OCIsInJlY2VudGx5LXZpZXdlZCI6IiIsIkNQVC1pZCI6InDCp8OZXHUwMDExVkdyXHUwMDA0bnnCr3c3wozDjsKBIiwiZXhwZXJpZW5jZSI6IiIsInRyayI6IiJ9LCJuYmYiOjE3MTM2NjgzMDMsImlhdCI6MTcxMzY2ODMwM30.N_cH19fwIzIcbrGDp2EFgWiPzwWA0wR6bUlpe_AQCEU",
			id: 43,
		},
	],
	deepScrape: false,
	"filters.fromMembers": [
		"https://www.linkedin.com/in/adrian-%F0%9F%9F%A3-b-b52348181/recent-activity/all/?datePosted=%22past-24h%22&origin=FACETED_SEARCH&sid=eNU&sortBy=%22date_posted%22",
	],
	maxDelay: 5,
	minDelay: 2,
	startPage: 1,
	strictMode: false,
};

(async () => {
	// Run the Actor and wait for it to finish
	const run = await client.actor("kfiWbq3boy3dWKbiL").call(input);

	// Fetch and print Actor results from the run's dataset (if any)
	console.log("Results from dataset");
	const { items } = await client.dataset(run.defaultDatasetId).listItems();
	items.forEach((item) => {
		console.dir(item);
	});
})();
